### ISSUE TITLE
Something is not right to me.

### ISSUE THREAD

**Issue by snoweye** [RBigData/pbdDMAT#23]
snoweye@vb2:~/work-my/linux$ cat a.r
suppressMessages(library(pbdDMAT, quiet = TRUE))
init.grid()

if(comm.rank() == 0){
  x <- matrix(1:16, 4)
  print(x)
  print(sum(colMeans(x)))
} else {
  x <- NULL
}

x <- as.ddmatrix(x)
y <- sum(colMeans(x))
comm.print(y)

finalize()
snoweye@vb2:~/work-my/linux$ mpiexec -np 4 Rscript a.r
Using 2x2 for the default grid size

```
 [,1] [,2] [,3] [,4]
```

[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16
[1] 34
COMM.RANK = 0
[1] 68

**Comment by wrathematics** [comment]
Fixed in latest.
