### ISSUE TITLE
Biting warning created by rbind and is.ddmatrix

### ISSUE THREAD

**Issue by seblamydlc** [RBigData/pbdDMAT#24]
Calls to rbind create warnings when the pacakge pbdDMAT is loaded:

```
library(pbdDMAT)
library(data.table)
rbind(data.table(), data.table())
```

This comes from the fact that the rbind function was overridden in pbdDMAT. In pbdDMAT::rbind function there is a is.ddmatrix check. In this function you check if the object is a 'ddmatrix' with the following call:

`if (class(x) == "ddmatrix") 
`
The proper way to check if an object is of a given class is using 'is' (is(obj, class))

Hope this helps,

Thanks,
Sébastien

**Comment by wrathematics** [comment]
Sorry for the delay.

Thanks for the report! Fixed in the latest.
