### ISSUE TITLE
rbind interferes with other definitions of rbind

### ISSUE THREAD

**Issue by seblamydlc** [RBigData/pbdDMAT#25]
Hi guys!

Your definition of 'rbind' interferes with other definitions. You defined 'rbind' as a S4 generic method but the normal way to overload rbind is to use S3 syntax since it's an internal generic https://stat.ethz.ch/R-manual/R-devel/library/base/html/InternalMethods.html

I think that exporting `dmat.rbind2` as the S3method overloading `rbind` for the class 'ddmatrix' should do the trick.

Let me know if you need me to clarify my point!

Thanks for the good work!
Cheers!

**Comment by wrathematics** [comment]
Hey, sorry it took me so long to respond. I thought I already had :[

You're right; should be fixed in the latest. Thanks!
